### PR TITLE
Fallback for message:json rendering of simple messages

### PR DESCRIPTION
**Pull request by mkedwards**
Sorry, I realized just after you released v0.14 that the message:json refactor lost the fallback paths for non-JSON-capable message types.

### CODE REVIEW

**Comment by vy** [comment]
(No worries for the release, I did not push to Maven Central yet. Though thanks for the quick reaction.)

I did that change on purpose: If you are trying to access a `MultiformatMessage` JSON, failure to do so and falling back to its textual representation, IMHO, is contradicting with directives' purpose. Am I missing a point (or use case) here?

**Comment by mkedwards** [comment]
I'd like for it to do something reasonable with simple log lines, at least -- ones that aren't `MultiformatMessage`s anyway.  Otherwise we lose the messages from all the libraries that use simple log syntax.

**Comment by vy** [comment]
Ok, I will fix it. One more question: If `resolveText()` (called as a fallback) returns a null node and empty property exclusion is enabled, do you still want to produce a `{"message": null}` or exclude it all together.

**Comment by mkedwards** [comment]
I think either is reasonable.  The change I'm suggesting here simply does what getTextNode does, only wrapped inside a `{"message":...}`.

**Comment by mkedwards** [comment]
The interesting case that is a MultiformatMessage but doesn't support JSON is the `StructuredDataMessage`.  I _think_ it would be best (until it grows a JSON format) to call its `getFormattedMessage()`, which uses the default format, which is FULL.

**Comment by mkedwards** [comment]
And in case I forgot to say it, thanks for a _really_ useful component!

**Comment by vy** [comment]
Would you mind making a final check, please? Then I will cut the release.

**Comment by mkedwards** [comment]
What you pushed to master works great.  I like your change to null handling.  Thanks!

**Comment by vy** [comment]
For the records: Issue is resolved with changes addressed in #15.

**Pull request closed without merging**
